// <auto-generated />
namespace TeleViajes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class parqueTematico : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(parqueTematico));
        
        string IMigrationMetadata.Id
        {
            get { return "202011071612180_parqueTematico"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
